### ISSUE TITLE
Cookie message closing is not permanent

### ISSUE THREAD

**Issue by calumshep** [MultiCrew/copilot#12]
Closing the cookie message works, but it seems that it does not then set the cookie to prevent the message from appearing again on that browser.

**Comment by hcphoon01** [comment]
Requires change from `Cookie::queue()` to `return redirect()->back()->withCookie()`

**Comment by hcphoon01** [comment]
Fixed in https://github.com/MultiCrew/copilot/commit/80afcda3643829b3a379659e4f02e4e1159616b1
