### ISSUE TITLE
Implement proper error handling in account updating

### ISSUE THREAD

**Issue by calumshep** [MultiCrew/copilot#14]
Use Laravel validator to check form data.
Scope to check passwords match?

**Comment by hcphoon01** [comment]
Can use the Laravel `confirmation` validator  for password confirmationhttps://laravel.com/docs/6.x/validation#rule-confirmed

**Comment by calumshep** [comment]
Does c17fdee7580c1a1bc6f08d2813d1a6b4aeee922f implement this @hcphoon01?

**Comment by hcphoon01** [comment]
Yes, didnt realise there was an issue opened for this.
