### ISSUE TITLE
Great circle line on maps

### ISSUE THREAD

**Issue by inventor02** [MultiCrew/copilot#148]
**Is your feature request related to a problem? Please describe.**
A map with two points and a large gap between with nothing else plotted looks empty.

**Describe the solution you'd like**
A great circle line could be plotted on the map between the two airports.

**Describe alternatives you've considered**
Plotting the route would require much more additional data and processing, this is a simpler solution that still gets the job done.

**Comment by calumshep** [comment]
Do you have any ideas as to how this could be done where there are multiple departure and/or arrival airports?

**Comment by calumshep** [comment]
Yeah I guess that works. I don't feel the need to account for any potential use case outside of the obvious here
