### ISSUE TITLE
Convert all env() instances to config()

### ISSUE THREAD

**Issue by hcphoon01** [MultiCrew/copilot#149]
All instances of then `env`, aside from those in config files, should be changed over to `config` instances to aviod caching issues, 'custom' config items should be in their own files i.e. a `config/discord.php` file should be created to include the different variables for different Discord related items

Reference:
[https://stackoverflow.com/a/42393294/11028131](https://stackoverflow.com/a/42393294/11028131)

**Comment by calumshep** [comment]
This should be completed now that api branch is merged? @hcphoon01

**Comment by hcphoon01** [comment]
I dont know why it didn't automatically close, but yes

**Comment by calumshep** [comment]
"Fixes" isn't a linking keyword and it was just in a commit message - think it has to be mentioned properly in the PR for it to link. Thanks anyway.
