### ISSUE TITLE
Notification bell icon broken

### ISSUE THREAD

**Issue by hcphoon01** [MultiCrew/copilot#151]
Notification bell icon not showing number next to it when there is an unread notification, also pressing "Mark all as read" reads the notifications but does not clear them from the dropdown until after a page refresh

**Comment by calumshep** [comment]
Is this still a bug? Does it exist in production? Asking as incomplete or outdated npm compiled assets, or other CSS/JS issues, often lead to this.

**Comment by hcphoon01** [comment]
Tried on my local machine with all the correctly installed assets and all compiled
