### ISSUE TITLE
Add filter/search functionality to fleet

### ISSUE THREAD

**Issue by xplana** [MultiCrew/copilot#155]
The list of aircrafts will extend in volume rapidly. Therefor some major filters are needed here in order to able to be handled and browsed by users. 

I’d suggest  filters (as for now):

- by simulator
- by ac type
- by publisher (example aerosoft, toliss, pmdg....)
- by freeware/payware (to be included in database) 

In addition I’d suggest to remove the column ‚added by‘ since this is not relevant for aircrafts.

**Comment by calumshep** [comment]
Should implement JS data tables
