### ISSUE TITLE
Add ZULU and LOCAL time to top bar

### ISSUE THREAD

**Issue by xplana** [MultiCrew/copilot#157]
it would help a lot to have ZULU and LOCAL time displayed for example in the top bar (as in the picture) in order to help the users since probably some of us might have to look up at least the ZULU time repeatedly. 

<img width="1280" alt="times" src="https://user-images.githubusercontent.com/17392829/97775174-efdc4c80-1b5e-11eb-9b2a-f4e7e4386ef9.png">

**Comment by calumshep** [comment]
Will remove the zulu time from dispatch pages and replace with global time display in navbar
