### ISSUE TITLE
Add logic to flight join trait

### ISSUE THREAD

**Issue by hcphoon01** [MultiCrew/copilot#164]
Logic needs to be added to flight join trait to ensure that a single departure and single arrival airport are set before accepting request

**Comment by calumshep** [comment]
There's already logic to prevent a flight without a single dep and arr being dispatched. I personally think the steps of accepting a flight (and being matched with your copilot) and _then_ discussing dep and arr airports before deciding on a single one for each, and then dispatching, is better; having to decide on a single dep and arr before the request has two pilots would require them discussing it with each other but they're not put in contact until they are on the flight request so it's like skipping a step - does that make sense?

**Comment by hcphoon01** [comment]
Roger, I will need to update the API to comply with this logic

**Comment by calumshep** [comment]
Nice one GH

**Comment by hcphoon01** [comment]
(Its not closed as its still in `feature/api` not been merged into dev yet)

**Comment by calumshep** [comment]
Can you open a PR for it pls
