### ISSUE TITLE
Laravel Resource routes not working unless manually assigned

### ISSUE THREAD

**Issue by calumshep** [MultiCrew/copilot#23]
Using `::resource()` routes to automatically generate standard resource CRUD routes is not working for specific routes. See the comment in the web routes file for details. 

Manually assigning the routes in the same way to how the resource method should seems to solve this. Perhaps a Laravel bug?

**Comment by hcphoon01** [comment]
Fixed in cf885afb707e09e3c541af6b28388e101567d98f
