### ISSUE TITLE
Discord Connection

### ISSUE THREAD

**Issue by hcphoon01** [MultiCrew/copilot#59]
Add a section in the account page to include a connection button to connect the users discord account, if not already connected, and then something to show that their discord account is connected.

**Comment by hcphoon01** [comment]
Also create button to disconnect the users discord account, which will be linked to a method to set the id to null

**Comment by calumshep** [comment]
How does the connection logic work?

**Comment by hcphoon01** [comment]
It redirects the user to the discord login page, after that it redirects back to the account page and stores their discord ID in the users table

**Comment by calumshep** [comment]
Added in https://github.com/MultiCrew/copilot/commit/c7cf3152f7ffa41c19b544710df6550acd8b512b
