### ISSUE TITLE
Allow selection of any callsign/flight number

### ISSUE THREAD

**Issue by danielmdietz** [MultiCrew/copilot#92]
I am missing the function to change the airline call sign since I alway like to replicate real world flights I don’t want to fly with a fictional call sign like „Mc“. Any chances you could change the airline or make a selection in the future?

Or even link it with an data base. Like flying loww - lowi the System suggests AUA and maybe even the flightnumber (or a random one)

**Comment by calumshep** [comment]
A database of real-world flights, numbers and callsigns is something we'd love to implement but getting said database (and keeping it up-to-date) is a little out of our scope. If anyone can point us towards how to do this then that would be great but as far as I'm aware this data would come at a cost.
